name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Fullstack to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Frontend
        working-directory: ./client
        run: |
          npm install
          npm run build

      - name: Build Backend & Prisma
        working-directory: ./server
        run: |
          npm install
          npx prisma generate

      - name: Deploy to Render
        uses: render-examples/github-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          branch: main
          waitForCompletion: true
